# name of your github action
name: Build and Deploy

# this will help you specify where to run
on:
  push:
    branches: [ main ]

# this is where the magic happens, each job happens in parallel btw
jobs:

  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - run: npm run build
      - run: npm run doit
